"""
Interactive setup for email and Telegram notifications.

Usage:
    python -m src.automation.setup
"""

import os
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
ENV_FILE = PROJECT_ROOT / ".env"


def setup():
    print("\n⚾ Homer Tracker — Notification Setup")
    print("=" * 50)

    settings = {}

    # Email
    print("\n📧 Email Configuration (Gmail recommended)")
    print("   Leave blank to skip.\n")

    smtp_user = input("   SMTP username (email address): ").strip()
    if smtp_user:
        smtp_pass = input("   SMTP password (app password): ").strip()
        recipient = input(f"   Send to [{smtp_user}]: ").strip() or smtp_user
        settings["SMTP_HOST"] = "smtp.gmail.com"
        settings["SMTP_PORT"] = "587"
        settings["SMTP_USER"] = smtp_user
        settings["SMTP_PASSWORD"] = smtp_pass
        settings["EMAIL_RECIPIENT"] = recipient
        print("   ✅ Email configured!")
    else:
        print("   ⏭️  Skipped.")

    # Telegram
    print("\n💬 Telegram Configuration")
    print("   1. Message @BotFather on Telegram → /newbot")
    print("   2. Get your chat_id from @userinfobot")
    print("   Leave blank to skip.\n")

    tg_token = input("   Bot token: ").strip()
    if tg_token:
        tg_chat = input("   Chat ID: ").strip()
        settings["TELEGRAM_BOT_TOKEN"] = tg_token
        settings["TELEGRAM_CHAT_ID"] = tg_chat
        print("   ✅ Telegram configured!")
    else:
        print("   ⏭️  Skipped.")

    if not settings:
        print("\n   Nothing configured. Exiting.")
        return

    # Write .env file
    existing = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, val = line.partition("=")
                existing[key.strip()] = val.strip()

    existing.update(settings)

    lines = ["# Homer Tracker — notification settings",
             "# Auto-generated by setup. Do NOT commit this file.\n"]
    for key, val in existing.items():
        lines.append(f'{key}="{val}"')

    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"\n💾 Settings saved to {ENV_FILE}")
    print("⚠️  Make sure .env is in your .gitignore!\n")


def setup_launchd() -> None:
    """Generate and install the macOS launchd plist."""
    print("\n⏰ LAUNCHD SETUP")
    print("-" * 40)
    print("  This schedules Homer Tracker to run automatically every day.\n")

    venv_python = os.path.join(PROJECT_ROOT, "venv", "bin", "python")
    if not os.path.exists(venv_python):
        venv_python = input(f"  Path to python [{os.sys.executable}]: ").strip() or os.sys.executable

    hour = input("  Run daily at what hour? (24h, e.g. 11 = 11 AM) [11]: ").strip() or "11"
    minute = input("  Minute [00]: ").strip() or "00"

    plist_name = "com.homertracker.daily"
    plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{plist_name}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{venv_python}</string>
        <string>-m</string>
        <string>src.automation.runner</string>
    </array>
    <key>WorkingDirectory</key>
    <string>{PROJECT_ROOT}</string>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>{int(hour)}</integer>
        <key>Minute</key>
        <integer>{int(minute)}</integer>
    </dict>
    <key>StandardOutPath</key>
    <string>{PROJECT_ROOT}/logs/launchd_stdout.log</string>
    <key>StandardErrorPath</key>
    <string>{PROJECT_ROOT}/logs/launchd_stderr.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin</string>
    </dict>
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>"""

    os.makedirs(os.path.join(PROJECT_ROOT, "logs"), exist_ok=True)

    launch_dir = Path.home() / "Library" / "LaunchAgents"
    launch_dir.mkdir(exist_ok=True)
    plist_path = launch_dir / f"{plist_name}.plist"
    plist_path.write_text(plist_content)

    local_copy = PROJECT_ROOT / f"{plist_name}.plist"
    local_copy.write_text(plist_content)

    os.system(f"launchctl unload {plist_path} 2>/dev/null")
    os.system(f"launchctl load {plist_path}")

    print(f"\n  ✅ Plist installed and loaded!")
    print(f"     {plist_path}")
    print(f"\n  📅 Runs daily at {hour}:{minute.zfill(2)}")
    print(f"\n  Useful commands:")
    print(f"    launchctl start {plist_name}     # Run now")
    print(f"    launchctl unload {plist_path}    # Disable")
    print(f"    launchctl load {plist_path}      # Re-enable")


def full_setup():
    """Run all setup steps interactively."""
    print("\n⚾ Homer Tracker — Full Setup")
    print("=" * 50)

    setup()

    print("\n⏰ Set up daily automation (launchd)?")
    if input("   Configure? [y/N]: ").strip().lower() == "y":
        setup_launchd()

    print("\n" + "=" * 50)
    print("  ✅ Setup complete! Verify with:")
    print("     python -m src.automation.runner --status")
    print("=" * 50 + "\n")


if __name__ == "__main__":
    full_setup()
